services:

  rabbitmq:
    image: bitnami/rabbitmq:latest
    hostname: rabbitmq
    container_name: rabbitmq-${COMPOSE_PROJECT_NAME}
    restart: always
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "4GB"
    networks:
      - nginxproxy
    ports:
      - '4369:4369'
      - '5551:5551'
      - '5552:5552'
      - '5672:5672'
      - 25672:25672 # (erlang) communication between the nodes and CLI tool
      - 15672:15672 # communication with the web management API 
    volumes:
       - rabbitmq-data:/bitnami
    environment:
      VIRTUAL_HOST: localhost:5672
      VIRTUAL_PORT: 15672
      RABBITMQ_NODE_PORT_NUMBER: 5672     
      RABBITMQ_MANAGEMENT_PORT_NUMBER: 15672
      RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS: true
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      
networks:
  nginxproxy:

volumes:
  rabbitmq-data: