services:

  seq:
    image: datalust/seq:latest
    hostname: seq
    container_name: seq-${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "4GB"
    networks:
      - nginxproxy
    ports:
      - 8082:80
      - 5341:5341
    volumes:
      - seq-data:/data
    environment:
      ACCEPT_EULA: Y
      VIRTUAL_HOST: localhost:8081
      VIRTUAL_PORT: 80
      SEQ_FIRSTRUN_ADMINPASSWORDHASH: ${SEQ_FIRSTRUN_ADMINPASSWORDHASH}
      SEQ_STORAGE_SECRETKEY: ${SEQ_STORAGE_SECRETKEY}
      
networks:
  nginxproxy:

volumes:
  seq-data: