services:
  minio:
    image: minio/minio:latest
    hostname: minio
    container_name: minio-${COMPOSE_PROJECT_NAME}
    command: server --console-address ":9001" /data
    restart: always
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "4GB"
    networks:
      - nginxproxy
    ports:
      - "9005:9000"
      - "9006:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      
networks:
  nginxproxy:

volumes:
  minio-data: